### ISSUE TITLE
Therapist trading is break all trading menus

### ISSUE THREAD

**Issue by layer26** [kobrakon/SPO_DEV#6]
# Environment information
- SPO - 0.13.1
- SPT-AKI - 2.3.1
- EFT - 0.12.12.15.17349 (Patched from 0.12.12.15.17639 by AKI Patcher)

# Summary
When enter to Therapist trading menu, there is nothing exists. in this context, other traders is not any effected.

![image](https://user-images.githubusercontent.com/16622747/165987056-9ca78e02-245e-4498-ba8b-e8fba2f09567.png)

However, if click Therapist's `BUY` or `SELL` menu button, other trader's menu tab buttons are not response. and it effected to all traders.

This 'unresponse' state is fixed when restarting client or playing game and leave.

# Effects
- Cannot trade anythings from Therapist
- (Some cases) Cannot switch (all) traders's tab

# Exception logs
# Server
This exception is threw when player entered to Therapist's `SERVICES` menu. (i'm not sure but it looks likes no related to this bug)
```
[ERROR] Trace:
TypeError: suits is not iterable
    at Function.getTraderSuits (D:\Security\Game\Battlestate Games\EFT_0.12.12.15.17639\obj\src\controllers\CustomizationController.js:38:28)
    at Object.getTraderSuits [as aki] (D:\Security\Game\Battlestate Games\EFT_0.12.12.15.17639\obj\src\callbacks\CustomizationCallbacks.js:20:61)
    at Function.getResponse (D:\Security\Game\Battlestate Games\EFT_0.12.12.15.17639\obj\src\routers\HttpRouter.js:42:30)
    at Function.sendResponse (D:\Security\Game\Battlestate Games\EFT_0.12.12.15.17639\obj\src\servers\HttpServer.js:149:33)
    at Inflate.cb (D:\Security\Game\Battlestate Games\EFT_0.12.12.15.17639\obj\src\servers\HttpServer.js:195:32)
    at Inflate.zlibBufferOnEnd (zlib.js:153:10)
    at Inflate.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
# Client
This exception is threw when player entered to Therapist trading screen.
```
2022-04-30 01:37:41.064 +09:00|0.12.12.15.17349|Error|Default|ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
GClass1873.IsCurrencyId (System.String id) (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
EFT.UI.HandbookFilterPanel.RegisterItem (EFT.InventoryLogic.Item item) (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
EFT.UI.HandbookFilterPanel.PreInit (GClass1689 assortment, System.Collections.Generic.IEnumerable`1[T] items) (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
EFT.UI.DragAndDrop.TradingGridView.Show (System.Collections.Generic.IEnumerable`1[T] items, GClass2147 sourceContext, GClass1689 assortment, GClass2100 inventoryController, EFT.UI.ItemUiContext itemUiContext, System.Boolean raiseEvents) (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
EFT.UI.TraderDealScreen.method_7 (System.Boolean raiseEvents) (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
EFT.UI.TraderDealScreen.method_4 (EFT.Profile+GClass1454 traderInfo) (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
EFT.UI.TraderDealScreen.method_3 () (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
EFT.UI.TraderDealScreen.method_0 () (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
GClass2541.Invoke () (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
GClass1692+Class1485.method_0 (Comfort.Common.Result`2[T0,T1] result) (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
GClass1692+Struct371.MoveNext () (at <2b480cfba3fd4ee98dd33579220a6fc8>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <42787f1e61944d5b8428e15b82ac9c47>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class293:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()
```

# Reproduce
1. Entered to Therapist trading menu.
2. Click `BUY` or `SELL` trading menu buttons.
3. Change trader, and click `BUY` or `SELL`
4. You can see other trader's all menu buttons doesn't works.

# Attachments
- Profile data : [profiles.zip](https://github.com/kobrakon/SPO_DEV/files/8592386/profiles.zip)

**Comment by kobrakon** [comment]
conflicts with flealock and the new traders mod are causing this issue, will be patched soon
